# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree_course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sub_category',
        ),
        migrations.AlterUniqueTogether(
            name='coursechapter',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='coursechapter',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='recommend_courses',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='teachers',
        ),
        migrations.AlterUniqueTogether(
            name='courseoutline',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='courseoutline',
            name='course_detail',
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='coursesubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='degreecourse',
            name='teachers',
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='homework',
            name='chapter',
        ),
        migrations.AlterUniqueTogether(
            name='oftenaskedquestion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='oftenaskedquestion',
            name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='pricepolicy',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='pricepolicy',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='degree_course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.DeleteModel(
            name='CourseChapter',
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
        migrations.DeleteModel(
            name='CourseOutline',
        ),
        migrations.DeleteModel(
            name='CourseSection',
        ),
        migrations.DeleteModel(
            name='CourseSubCategory',
        ),
        migrations.DeleteModel(
            name='DegreeCourse',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='OftenAskedQuestion',
        ),
        migrations.DeleteModel(
            name='PricePolicy',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
